#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# 米高智能客服微信小程序 — 测试环境接入向导
# 目标：拿到微信 AppID/AppSecret → 写入服务器 .env.admin-api → 本地配置 → 真机调试。
# 你需要做的：在微信公众平台后台复制两个值；其余（服务器配置/本地配置）脚本自动完成。
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# ---- MIGAO 专用配置（按仓库实际情况硬编码，勿改） ----
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
MINI_APP_DIR="$REPO_ROOT/frontend/mini-app"
ENV_FILE="$MINI_APP_DIR/.env.local"            # gitignore 已覆盖 .env.*，可安全存 AppID
WX_API_DOMAIN="https://app.migaozn.com"        # 小程序唯一合法域名（nginx 已分流 /api/chat/ 与 /api/）
SWAS_INSTANCE_ID="b23c69e599524b1da719734f72e6a0e3"
SWAS_REGION="cn-hangzhou"
SERVER_ENV_FILE="/opt/migao-deploy/.env.admin-api"
SERVER_COMPOSE_DIR="/opt/migao-deploy"

TOTAL_STAGES=7

banner "米高小程序测试环境接入"

# server_run "name" "shell 命令" — 通过 aliyun CLI 在 SWAS 服务器执行命令并轮询结果。
# 失败不中断（记录 SKIPPED），避免因单条命令失败导致向导整体退出。
server_run() {
  local name="$1" cmd="$2" invoke_id out status tries
  say "  ↻ 服务器执行: $name"
  out=$(aliyun swas-open run-command \
    --command-content "$cmd" \
    --instance-id "$SWAS_INSTANCE_ID" \
    --biz-region-id "$SWAS_REGION" \
    --name "$name" --type RunShellScript 2>&1) || {
      SKIPPED+=("服务器命令 $name（aliyun CLI 调用失败）")
      warn "aliyun CLI 调用失败"; return 1
    }
  invoke_id=$(printf '%s' "$out" | sed -n 's/.*"InvokeId": *"\([^"]*\)".*/\1/p' | head -1)
  [[ -n "$invoke_id" ]] || { SKIPPED+=("服务器命令 $name（未拿到 InvokeId）"); warn "未拿到 InvokeId"; return 1; }
  tries=0
  while (( tries < 20 )); do
    sleep 3
    out=$(aliyun swas-open describe-invocation-result \
      --invoke-id "$invoke_id" --instance-id "$SWAS_INSTANCE_ID" \
      --biz-region-id "$SWAS_REGION" 2>&1 || true)
    status=$(printf '%s' "$out" | sed -n 's/.*"InvocationStatus": *"\([^"]*\)".*/\1/p' | head -1)
    if [[ "$status" == "Success" ]]; then
      exitcode=$(printf '%s' "$out" | sed -n 's/.*"ExitCode": *\([0-9-]*\).*/\1/p' | head -1)
      if [[ "$exitcode" == "0" ]]; then
        printf '  %s✓ server %s OK%s\n' "$GREEN" "$RESET" "$name"
      else
        SKIPPED+=("服务器命令 $name（ExitCode=$exitcode）")
        warn "服务器命令 $name 退出码 $exitcode"
      fi
      return 0
    elif [[ "$status" == "Failed" || "$status" == "Timeout" ]]; then
      SKIPPED+=("服务器命令 $name（状态 $status）")
      warn "服务器命令 $name 状态 $status"
      return 1
    fi
    tries=$((tries + 1))
  done
  SKIPPED+=("服务器命令 $name（轮询超时）")
  warn "服务器命令 $name 轮询超时，稍后可手动核对"
}

# ── Stage 1 · 登录微信公众平台 ────────────────────────────────────────────
stage "登录微信公众平台"
say "请用【管理员微信】扫码登录微信公众平台。"
open_url "https://mp.weixin.qq.com"
step "手机微信扫码 → 确认登录。"
step "登录后确认左上角是你申请的「智能客服」小程序（gh_7cd4c1b3b76f）。"
pause "登录完成并进入小程序后台后，回车继续"

# ── Stage 2 · 复制 AppID ──────────────────────────────────────────────────
stage "复制 AppID"
say "AppID 是小程序的唯一身份标识（wx 开头），要填入小程序与后端。"
step "左侧菜单：开发管理 → 开发设置。"
step "在「开发者ID」区域找到 AppID（形如 wx4f2a...）。"
step "点复制按钮，粘贴到下面。"
ask WECHAT_MINI_APPID "粘贴 AppID（wx 开头）:"
if [[ "$WECHAT_MINI_APPID" != wx* ]]; then
  warn "AppID 应以 wx 开头，请核对是否复制完整"
  pause "确认后回车继续"
fi
write_env WECHAT_MINI_APPID "$WECHAT_MINI_APPID"

# ── Stage 3 · 生成并复制 AppSecret ────────────────────────────────────────
stage "生成并复制 AppSecret"
say "AppSecret 是后端调微信接口的密钥（登录换 openid 用），只显示一次，请妥善保管。"
step "仍在「开发设置」页面，往下找到 AppSecret 区域。"
step "若从未生成过：点「生成」→ 管理员扫码确认 → 显示明文。"
step "若已生成但忘了：点「重置」→ 扫码确认 → 显示新的明文（旧密钥立即失效）。"
step "立即复制明文粘贴到下面（输入不回显，请勿外泄）。"
ask_secret WECHAT_MINI_SECRET "粘贴 AppSecret（32 位）:"
if [[ -z "$WECHAT_MINI_SECRET" ]]; then
  warn "AppSecret 不能为空"
  pause "回车继续"
fi
write_env WECHAT_MINI_SECRET "$WECHAT_MINI_SECRET"

# ── Stage 4 · 写入服务器 .env.admin-api 并重启 admin-api ──────────────────
stage "配置服务器环境变量（自动）"
say "用阿里云 CLI 把 AppID/AppSecret 写入服务器 $SERVER_ENV_FILE 并重启 admin-api。"
server_run "set-wechat-appid" \
  "sed -i 's|^WECHAT_MINI_APPID=.*|WECHAT_MINI_APPID=$WECHAT_MINI_APPID|' $SERVER_ENV_FILE && grep -q '^WECHAT_MINI_APPID=' $SERVER_ENV_FILE || echo 'WECHAT_MINI_APPID=$WECHAT_MINI_APPID' >> $SERVER_ENV_FILE"
server_run "set-wechat-secret" \
  "sed -i 's|^WECHAT_MINI_SECRET=.*|WECHAT_MINI_SECRET=$WECHAT_MINI_SECRET|' $SERVER_ENV_FILE && grep -q '^WECHAT_MINI_SECRET=' $SERVER_ENV_FILE || echo 'WECHAT_MINI_SECRET=$WECHAT_MINI_SECRET' >> $SERVER_ENV_FILE"
server_run "recreate-admin-api" \
  "cd $SERVER_COMPOSE_DIR && docker compose up -d --force-recreate admin-api"
say "重启后后端会用真实 AppID 调微信 code2Session（不再走 mock）。"
pause "确认服务器配置结果后回车继续"

# ── Stage 5 · 本地小程序配置 ───────────────────────────────────────────────
stage "本地小程序配置（自动）"
say "把测试环境 API 域名写进 $ENV_FILE，构建时自动指向线上后端。"
write_env TARO_APP_API_URL "$WX_API_DOMAIN"
write_env TARO_APP_AI_API_URL "$WX_API_DOMAIN"
# Taro 支持 TARO_APP_ID 覆盖构建产物 appid（dist/project.config.json），与
# project.private.config.json 双保险，保证真机调试与上传都用真实 AppID。
write_env TARO_APP_ID "$WECHAT_MINI_APPID"
if [[ ! -f "$MINI_APP_DIR/project.private.config.json" ]]; then
  cat > "$MINI_APP_DIR/project.private.config.json" <<EOF
{
  "description": "本地私有配置（不入库）：真实 AppID 供真机调试",
  "appid": "$WECHAT_MINI_APPID",
  "projectname": "migao-mini"
}
EOF
  printf '  %s✓ wrote%s project.private.config.json（真实 AppID，不污染 git）\n' "$GREEN" "$RESET"
  if ! grep -q "project.private.config.json" "$REPO_ROOT/.gitignore" 2>/dev/null; then
    printf 'project.private.config.json\n' >> "$REPO_ROOT/.gitignore"
    printf '  %s✓ wrote%s .gitignore 追加 project.private.config.json\n' "$GREEN" "$RESET"
  fi
else
  note "project.private.config.json 已存在，请人工确认其中 appid 为 $WECHAT_MINI_APPID"
fi
pause "确认本地配置后回车继续"

# ── Stage 6 · （可选）配置 request 合法域名 ────────────────────────────────
stage "（可选）配置 request 合法域名"
say "真机调试模式可跳过域名校验，这一步可选。"
say "若以后要用「预览二维码 / 体验版」发给同事扫码，则必须配置："
step "微信公众平台：开发管理 → 开发设置 → 服务器域名。"
step "request 合法域名添加：$WX_API_DOMAIN"
step "确认该域名已部署 HTTPS（当前已验证 TLS 正常）且小程序备案完成。"
if confirm "现在去配置合法域名？（真机调试可跳过）"; then
  open_url "https://mp.weixin.qq.com"
  pause "在服务器域名处添加 $WX_API_DOMAIN 后回车继续"
else
  note "跳过合法域名配置——真机调试不受影响。"
fi

# ── Stage 7 · 构建 + 真机调试指引 ─────────────────────────────────────────
stage "构建小程序 + 真机调试"
say "构建小程序（产出 dist）："
step "cd $MINI_APP_DIR && npm run build:weapp"
step "打开「微信开发者工具」→ 导入项目 → 目录选 $MINI_APP_DIR"
step "AppID 选择「使用真实 AppID」→ 确认 project.private.config.json 已带入 $WECHAT_MINI_APPID"
step "工具栏点「真机调试」→ 手机微信扫码 → 进入调试会话"
step "手机上登录/对话，验证后端真实 code2Session 链路"
say "注意事项："
note "  · 若 AI 对话无响应，检查 https://app.migaozn.com/api/chat/send 可达性"
note "  · 后端重启后首次登录会真实调用微信接口，失败时后端日志会提示 errcode"

finish

printf '\n%s 完成后可用 curl 自检：%s\n' "$DIM" "$RESET"
printf '    curl -s https://app.migaozn.com/api/health -o /dev/null -w "%%{http_code}\\n"\n'
printf '%s  服务器端校验：aliyun swas-open run-command ...（grep WECHAT %s）%s\n' "$DIM" "$SERVER_ENV_FILE" "$RESET"
